# Build only pushed (merged) master or any pull request. This avoids the
# pull request to be build twice.
branches:
  only:
    - master

language: csharp
solution: TikTok.sln
os:
  - linux
  - windows
  - osx

dotnet: 2.2.0
mono: none
git:
  depth: 1
  quiet: true

install:
- nuget restore TikTok.sln
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TikTok.sln
  - dotnet restore
  - dotnet build
  - dotnet test
