@startuml naam
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(lid, "Lid")
Person(medewerker, "Medewerker")
Person(beheerder, "Beheerder")
Person(wedstrijdCom, "Wedstrijdcommisaris")
Person(matCom, "Materiaalcommisaris")


System_Boundary(reserveerSysteem, "Reserveer Systeem"){
    Container(app, "Roei-Je-Rot Desktop App", "C#, .Net Core, WPF")   
    Container(logic, "Roei-Je-Rot Logica", "C#, .Net Core")
    
    ContainerDb(db, "Roei-Je-Rot Database", "MS-SQL")

    Rel(logic, db, "Stuurt aan")
    Rel(app, logic, "Gebruikt")
}

Rel(lid, app, "Maakt reserveringen met")
Rel(medewerker, app, "Boten innemen en uitnemen en schade melden")
Rel(beheerder, app, "Nieuwe boten en leden aanmaken en beheren")
Rel(wedstrijdCom, app, "Wedstrijden organiseren en beheren")
Rel(matCom, app, "Handelt schade af")

@enduml